name: MainContainer-Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd MainContainer
        npm install
        npm run build
      env: 
        PUBLIC_CONTAINER_DOMAIN: ${{ secrets.PUBLIC_CONTAINER_DOMAIN }}
        PRIVATE_CONTAINER_DOMAIN: ${{ secrets.PRIVATE_CONTAINER_DOMAIN }}
        
    - name: Firebase Deploy
      run: |
        cd MainContainer
        sudo npm install -g firebase-tools
        firebase use prod && firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}