name: MainContainer-Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd MainContainer
        npm install
        npm run build
      env: 
        PUBLIC_CONTAINER_DOMAIN: ${{ secrets.PUBLIC_CONTAINER_DOMAIN }}
        PRIVATE_CONTAINER_DOMAIN: ${{ secrets.PRIVATE_CONTAINER_DOMAIN }}
        
    - name: Firebase Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        entrypoint: MainContainer
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CUREFIT_B189D }}'
        projectId: container-main
        channelId: live